<?php
namespace Router;

use Illuminate\Container\Container;
use Middleware\Cors;

class Admin {

  static function Init(){
    // 允许跨域请求
    Cors::Init();
    // 路由
    $app = Container::getInstance();
    $app['router']->group(['namespace'=>'App\Admin', 'prefix' => 'admin'], function($router){
      // 首页
      $router->get('', "Index@Index");
      $router->post('index/holiday', "Index@Holiday");
      $router->post('index/get_select', "Index@GetSelect");
      $router->post('index/stock', "Index@Stock");
      $router->post('index/list', "Index@List");
      // 登录
      $router->post('user/login', "User@Login");
      $router->post('user/token', "User@Token");
      $router->get('user/vcode/{uname}', "User@Vcode");
      $router->post('user/get_vcode', "User@GetVcode");
      $router->post('user/change_passwd', "User@ChangePasswd");
      $router->post('user/change_uinfo', "User@ChangeUinfo");
      $router->post('user/upimg', "User@Upimg");
      // 消息
      $router->get('msg/socket', "Msg@Socket");
      $router->post('msg/list', "Msg@List");
      $router->post('msg/sea', "Msg@Sea");
      $router->post('msg/read', "Msg@Read");
      $router->post('msg/del', "Msg@Del");
      $router->post('msg/oss_sgin', "Msg@OssSgin");
      // 文件管理
      $router->post('sys_file/list', "SysFile@List");
      $router->post('sys_file/mkdir', "SysFile@Mkdir");
      $router->post('sys_file/rename', "SysFile@Rename");
      $router->post('sys_file/upload', "SysFile@Upload");
      $router->post('sys_file/down', "SysFile@Down");
      $router->post('sys_file/remove', "SysFile@Remove");
      // 系统用户
      $router->post('sys_user/total', "SysUser@Total");
      $router->post('sys_user/list', "SysUser@List");
      $router->post('sys_user/save', "SysUser@Save");
      $router->post('sys_user/del', "SysUser@Del");
      $router->post('sys_user/export', "SysUser@Export");
      $router->post('sys_user/get_select', "SysUser@GetSelect");
      $router->post('sys_user/get_perm', "SysUser@GetPerm");
      // 系统菜单
      $router->post('sys_menus/total', "SysMenus@Total");
      $router->post('sys_menus/list', "SysMenus@List");
      $router->post('sys_menus/save', "SysMenus@Save");
      $router->post('sys_menus/del', "SysMenus@Del");
      $router->post('sys_menus/export', "SysMenus@Export");
      $router->post('sys_menus/get_menus_all', "SysMenus@GetMenusAll");
      $router->post('sys_menus/get_menus_perm', "SysMenus@GetMenusPerm");
      // 系统角色
      $router->post('sys_role/total', "SysRole@Total");
      $router->post('sys_role/list', "SysRole@List");
      $router->post('sys_role/save', "SysRole@Save");
      $router->post('sys_role/del', "SysRole@Del");
      $router->post('sys_role/export', "SysRole@Export");
      $router->post('sys_role/get_perm', "SysRole@GetPerm");
      // 静态页面
      $router->post('web_html/total', "WebHtml@Total");
      $router->post('web_html/list', "WebHtml@List");
      $router->post('web_html/save', "WebHtml@Save");
      $router->post('web_html/del', "WebHtml@Del");
      $router->post('web_html/export', "WebHtml@Export");
      // 组织架构
      $router->post('erp_base_organization/total', "ErpBaseOrganization@Total");
      $router->post('erp_base_organization/list', "ErpBaseOrganization@List");
      $router->post('erp_base_organization/save', "ErpBaseOrganization@Save");
      $router->post('erp_base_organization/del', "ErpBaseOrganization@Del");
      $router->post('erp_base_organization/export', "ErpBaseOrganization@Export");
      // 店铺管理
      $router->post('erp_base_shop/total', "ErpBaseShop@Total");
      $router->post('erp_base_shop/list', "ErpBaseShop@List");
      $router->post('erp_base_shop/save', "ErpBaseShop@Save");
      $router->post('erp_base_shop/del', "ErpBaseShop@Del");
      $router->post('erp_base_shop/export', "ErpBaseShop@Export");
      $router->post('erp_base_shop/get_select', "ErpBaseShop@GetSelect");
      // 主仓&分仓
      $router->post('erp_base_partner/total', "ErpBasePartner@Total");
      $router->post('erp_base_partner/list', "ErpBasePartner@List");
      $router->post('erp_base_partner/save', "ErpBasePartner@Save");
      $router->post('erp_base_partner/del', "ErpBasePartner@Del");
      $router->post('erp_base_partner/export', "ErpBasePartner@Export");
      $router->post('erp_base_partner/get_select', "ErpBasePartner@GetSelect");
      // 品牌管理
      $router->post('erp_base_brand/total', "ErpBaseBrand@Total");
      $router->post('erp_base_brand/list', "ErpBaseBrand@List");
      $router->post('erp_base_brand/save', "ErpBaseBrand@Save");
      $router->post('erp_base_brand/del', "ErpBaseBrand@Del");
      $router->post('erp_base_brand/export', "ErpBaseBrand@Export");
      $router->post('erp_base_brand/get_select', "ErpBaseBrand@GetSelect");
      // 分类管理
      $router->post('erp_base_category/total', "ErpBaseCategory@Total");
      $router->post('erp_base_category/list', "ErpBaseCategory@List");
      $router->post('erp_base_category/save', "ErpBaseCategory@Save");
      $router->post('erp_base_category/del', "ErpBaseCategory@Del");
      $router->post('erp_base_category/export', "ErpBaseCategory@Export");
      $router->post('erp_base_category/get_select', "ErpBaseCategory@GetSelect");
      // 供应商
      $router->post('erp_base_supplier/total', "ErpBaseSupplier@Total");
      $router->post('erp_base_supplier/list', "ErpBaseSupplier@List");
      $router->post('erp_base_supplier/save', "ErpBaseSupplier@Save");
      $router->post('erp_base_supplier/del', "ErpBaseSupplier@Del");
      $router->post('erp_base_supplier/export', "ErpBaseSupplier@Export");
      $router->post('erp_base_supplier/import', "ErpBaseSupplier@Import");
      $router->post('erp_base_supplier/get_select', "ErpBaseSupplier@GetSelect");
      $router->post('erp_base_supplier/get_info', "ErpBaseSupplier@GetInfo");
      // 商品
      $router->post('erp_goods/barcode', "ErpGoods@Barcode");
      $router->post('erp_goods/barcode_print', "ErpGoods@BarcodePrint");
      $router->post('erp_goods/info', "ErpGoods@Info");
      $router->post('erp_goods/direct', "ErpGoods@Direct");
      $router->post('erp_goods/direct_export', "ErpGoods@DirectExport");
      $router->post('erp_goods/stock', "ErpGoods@Stock");
      $router->post('erp_goods/logs', "ErpGoods@Logs");
      $router->post('erp_goods/up_img', "ErpGoods@UpImg");
      $router->post('erp_goods/remove_img', "ErpGoods@RemoveImg");
      // 商品-资料
      $router->post('erp_goods_info/total', "ErpGoodsInfo@Total");
      $router->post('erp_goods_info/list', "ErpGoodsInfo@List");
      $router->post('erp_goods_info/save', "ErpGoodsInfo@Save");
      $router->post('erp_goods_info/del', "ErpGoodsInfo@Del");
      $router->post('erp_goods_info/export', "ErpGoodsInfo@Export");
      $router->post('erp_goods_info/import', "ErpGoodsInfo@Import");
      $router->post('erp_goods_info/exchange', "ErpGoodsInfo@Exchange");
      $router->post('erp_goods_info/status', "ErpGoodsInfo@Status");
      $router->post('erp_goods_info/get_select', "ErpGoodsInfo@GetSelect");
      // 商品-日志
      $router->post('erp_goods_log/total', "ErpGoodsLog@Total");
      $router->post('erp_goods_log/list', "ErpGoodsLog@List");
      $router->post('erp_goods_log/del', "ErpGoodsLog@Del");
      $router->post('erp_goods_log/export', "ErpGoodsLog@Export");
      // 商品-库存
      $router->post('erp_goods_stock/total', "ErpGoodsStock@Total");
      $router->post('erp_goods_stock/list', "ErpGoodsStock@List");
      $router->post('erp_goods_stock/save', "ErpGoodsStock@Save");
      $router->post('erp_goods_stock/del', "ErpGoodsStock@Del");
      $router->post('erp_goods_stock/export', "ErpGoodsStock@Export");
      $router->post('erp_goods_stock/get_select', "ErpGoodsStock@GetSelect");
      // 库存-采购入库
      $router->post('erp_purchase_in/total', "ErpPurchaseIn@Total");
      $router->post('erp_purchase_in/list', "ErpPurchaseIn@List");
      $router->post('erp_purchase_in/save', "ErpPurchaseIn@Save");
      $router->post('erp_purchase_in/del', "ErpPurchaseIn@Del");
      $router->post('erp_purchase_in/push', "ErpPurchaseIn@Push");
      $router->post('erp_purchase_in/revoke', "ErpPurchaseIn@Revoke");
      $router->post('erp_purchase_in/export', "ErpPurchaseIn@Export");
      $router->post('erp_purchase_in/get_select', "ErpPurchaseIn@GetSelect");
      $router->post('erp_purchase_in/goods_list', "ErpPurchaseIn@GoodsList");
      $router->post('erp_purchase_in/goods_add', "ErpPurchaseIn@GoodsAdd");
      $router->post('erp_purchase_in/goods_remove', "ErpPurchaseIn@GoodsRemove");
      $router->post('erp_purchase_in/goods_num', "ErpPurchaseIn@GoodsNum");
      $router->post('erp_purchase_in/goods_safety', "ErpPurchaseIn@GoodsSafety");
      $router->post('erp_purchase_in/goods_price', "ErpPurchaseIn@GoodsPrice");
      // 库存-入库等待
      $router->post('erp_purchase_in_push/total', "ErpPurchaseInPush@Total");
      $router->post('erp_purchase_in_push/list', "ErpPurchaseInPush@List");
      $router->post('erp_purchase_in_push/push', "ErpPurchaseInPush@Push");
      $router->post('erp_purchase_in_push/revoke', "ErpPurchaseInPush@Revoke");
      $router->post('erp_purchase_in_push/export', "ErpPurchaseInPush@Export");
      $router->post('erp_purchase_in_push/get_select', "ErpPurchaseInPush@GetSelect");
      $router->post('erp_purchase_in_push/goods_list', "ErpPurchaseInPush@GoodsList");
      // 库存-采购退货
      $router->post('erp_purchase_out/total', "ErpPurchaseOut@Total");
      $router->post('erp_purchase_out/list', "ErpPurchaseOut@List");
      $router->post('erp_purchase_out/save', "ErpPurchaseOut@Save");
      $router->post('erp_purchase_out/del', "ErpPurchaseOut@Del");
      $router->post('erp_purchase_out/push', "ErpPurchaseOut@Push");
      $router->post('erp_purchase_out/revoke', "ErpPurchaseOut@Revoke");
      $router->post('erp_purchase_out/explode', "ErpPurchaseOut@Explode");
      $router->post('erp_purchase_out/export', "ErpPurchaseOut@Export");
      $router->post('erp_purchase_out/get_select', "ErpPurchaseOut@GetSelect");
      $router->post('erp_purchase_out/goods_list', "ErpPurchaseOut@GoodsList");
      $router->post('erp_purchase_out/goods_add', "ErpPurchaseOut@GoodsAdd");
      $router->post('erp_purchase_out/goods_remove', "ErpPurchaseOut@GoodsRemove");
      $router->post('erp_purchase_out/goods_num', "ErpPurchaseOut@GoodsNum");
      $router->post('erp_purchase_out/goods_safety', "ErpPurchaseOut@GoodsSafety");
      $router->post('erp_purchase_out/goods_price', "ErpPurchaseOut@GoodsPrice");
      // 库存-退货等待
      $router->post('erp_purchase_out_push/total', "ErpPurchaseOutPush@Total");
      $router->post('erp_purchase_out_push/list', "ErpPurchaseOutPush@List");
      $router->post('erp_purchase_out_push/push', "ErpPurchaseOutPush@Push");
      $router->post('erp_purchase_out_push/revoke', "ErpPurchaseOutPush@Revoke");
      $router->post('erp_purchase_out_push/export', "ErpPurchaseOutPush@Export");
      $router->post('erp_purchase_out_push/get_select', "ErpPurchaseOutPush@GetSelect");
      $router->post('erp_purchase_out_push/goods_list', "ErpPurchaseOutPush@GoodsList");
      // 调拨出
      $router->post('erp_purchase_allocate_out/total', "ErpPurchaseAllocateOut@Total");
      $router->post('erp_purchase_allocate_out/list', "ErpPurchaseAllocateOut@List");
      $router->post('erp_purchase_allocate_out/save', "ErpPurchaseAllocateOut@Save");
      $router->post('erp_purchase_allocate_out/del', "ErpPurchaseAllocateOut@Del");
      $router->post('erp_purchase_allocate_out/push', "ErpPurchaseAllocateOut@Push");
      $router->post('erp_purchase_allocate_out/revoke', "ErpPurchaseAllocateOut@Revoke");
      $router->post('erp_purchase_allocate_out/export', "ErpPurchaseAllocateOut@Export");
      $router->post('erp_purchase_allocate_out/get_select', "ErpPurchaseAllocateOut@GetSelect");
      $router->post('erp_purchase_allocate_out/goods_list', "ErpPurchaseAllocateOut@GoodsList");
      $router->post('erp_purchase_allocate_out/goods_add', "ErpPurchaseAllocateOut@GoodsAdd");
      $router->post('erp_purchase_allocate_out/goods_remove', "ErpPurchaseAllocateOut@GoodsRemove");
      $router->post('erp_purchase_allocate_out/goods_num', "ErpPurchaseAllocateOut@GoodsNum");
      $router->post('erp_purchase_allocate_out/goods_safety', "ErpPurchaseAllocateOut@GoodsSafety");
      $router->post('erp_purchase_allocate_out/goods_price', "ErpPurchaseAllocateOut@GoodsPrice");
      // 调拨入
      $router->post('erp_purchase_allocate_in/total', "ErpPurchaseAllocateIn@Total");
      $router->post('erp_purchase_allocate_in/list', "ErpPurchaseAllocateIn@List");
      $router->post('erp_purchase_allocate_in/push', "ErpPurchaseAllocateIn@Push");
      $router->post('erp_purchase_allocate_in/revoke', "ErpPurchaseAllocateIn@Revoke");
      $router->post('erp_purchase_allocate_in/export', "ErpPurchaseAllocateIn@Export");
      $router->post('erp_purchase_allocate_in/get_select', "ErpPurchaseAllocateIn@GetSelect");
      $router->post('erp_purchase_allocate_in/goods_list', "ErpPurchaseAllocateIn@GoodsList");
      // 其它出入库
      $router->post('erp_order_inout/total', "ErpOrderInout@Total");
      $router->post('erp_order_inout/list', "ErpOrderInout@List");
      $router->post('erp_order_inout/save', "ErpOrderInout@Save");
      $router->post('erp_order_inout/del', "ErpOrderInout@Del");
      $router->post('erp_order_inout/push', "ErpOrderInout@Push");
      $router->post('erp_order_inout/export', "ErpOrderInout@Export");
      $router->post('erp_order_inout/get_select', "ErpOrderInout@GetSelect");
      $router->post('erp_order_inout/goods_list', "ErpOrderInout@GoodsList");
      $router->post('erp_order_inout/goods_add', "ErpOrderInout@GoodsAdd");
      $router->post('erp_order_inout/goods_remove', "ErpOrderInout@GoodsRemove");
      $router->post('erp_order_inout/goods_num', "ErpOrderInout@GoodsNum");
      $router->post('erp_order_inout/goods_safety', "ErpOrderInout@GoodsSafety");
      $router->post('erp_order_inout/goods_price', "ErpOrderInout@GoodsPrice");
    });
  }
}